@startuml

abstract class AbstractList
abstract AbstractCollection


abstract class AbstractTree

interface IList
interface ICollection
interface ITree

ITree <|-- AbstractTree
IList <|-- AbstractList
ICollection <|-- AbstractCollection

ICollection <|- IList
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml

